<a href="https://colab.research.google.com/github/BahruzHuseynov/HBrainery/blob/main/Medium/TensorFlow/Tf5_MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://lh5.googleusercontent.com/proxy/w7TfG4kk_vc9mIlqFClKIM04ezzFdKpr-6-OAyxyxPhrQEKltGLQZ2_muUxyfdxQFBLC796voIMHxiv3XAtz0KurCX7Iv41QgK6IL8euSpVk">

In [9]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, losses, optimizers, metrics, Sequential
from tensorflow.keras.datasets import mnist

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [4]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [5]:
def format(data):
    return data / 255.0

x_train = format(x_train)
x_test = format(x_test)

In [10]:
# Convert the labels to one-hot encoded vectors
y_train_ = tf.keras.utils.to_categorical(y_train, 10)
y_test_ = tf.keras.utils.to_categorical(y_test, 10)

model = Sequential([
    layers.Input(shape=(28, 28, 1)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train_, epochs=5, batch_size=64, validation_split=0.2)

Epoch 1/5
750/750 [==============================] - 6s 6ms/step - loss: 0.3326 - accuracy: 0.9063 - val_loss: 0.1618 - val_accuracy: 0.9533
Epoch 2/5
750/750 [==============================] - 3s 4ms/step - loss: 0.1389 - accuracy: 0.9582 - val_loss: 0.1204 - val_accuracy: 0.9650
Epoch 3/5
750/750 [==============================] - 3s 4ms/step - loss: 0.0997 - accuracy: 0.9695 - val_loss: 0.1095 - val_accuracy: 0.9672
Epoch 4/5
750/750 [==============================] - 3s 4ms/step - loss: 0.0789 - accuracy: 0.9762 - val_loss: 0.0995 - val_accuracy: 0.9691
Epoch 5/5
750/750 [==============================] - 4s 5ms/step - loss: 0.0636 - accuracy: 0.9800 - val_loss: 0.0974 - val_accuracy: 0.9707


In [14]:
test_loss, test_accuracy = model.evaluate(x_test, y_test_, verbose=2)
print(f'Test accuracy: {test_accuracy}')

313/313 - 1s - loss: 0.0839 - accuracy: 0.9734 - 511ms/epoch - 2ms/step
Test accuracy: 0.9733999967575073


### Training and Testing from scratch

In [15]:
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))

In [16]:
batch_size = 64
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)
test_dataset = test_dataset.batch(batch_size)

In [17]:
model = keras.Sequential(
    [
        layers.Flatten(input_shape=(28, 28)),
        layers.Dense(64, activation="relu"),
        layers.Dense(64, activation='relu'),
        layers.Dense(10, activation='softmax')
    ]
)

loss = losses.SparseCategoricalCrossentropy()
optimizer = optimizers.Adam(learning_rate=0.001)
metric = metrics.SparseCategoricalAccuracy()    # https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Accuracy

<img src = "https://miro.medium.com/v2/resize:fit:785/1*7EJEI7QkWd2dwhyVLjHQyA.png">

In [18]:
def applyGradient(model, x, y, loss, optimizer):
    with tf.GradientTape() as tape:
        predictions = model(x)
        lossValue = loss(y, predictions)

    gradients = tape.gradient(lossValue, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return lossValue, predictions

In [19]:
train_loss_list = []
train_acc_list = []
test_loss_list = []
test_acc_list = []

# Search about: # https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Accuracy
# metric.reset_states()
# metric.update_state()
# metric.result()

for epoch in range(5):
    metric.reset_states()  # Values are reset
    for batch, (x, y) in enumerate(train_dataset):
        lossValue, predictions = applyGradient(model, x, y, loss, optimizer)
        metric.update_state(y, predictions)

    train_loss_list.append(lossValue)
    train_acc_list.append(metric.result())

In [20]:
train_acc_list

[<tf.Tensor: shape=(), dtype=float32, numpy=0.9098667>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9592>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9694667>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9759333>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.97985>]

In [21]:
train_loss_list

[<tf.Tensor: shape=(), dtype=float32, numpy=0.02901771>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0774916>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.016430922>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.038686655>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.047352083>]

In [22]:
metric.reset_states()
for batch, (x, y) in enumerate(test_dataset):
    predictions = model(x)
    lossValue = loss(y, predictions)
    metric.update_state(y, predictions)

test_loss_list.append(lossValue)
test_acc_list.append(metric.result())

In [23]:
test_loss_list

[<tf.Tensor: shape=(), dtype=float32, numpy=0.00093998533>]

In [24]:
test_acc_list

[<tf.Tensor: shape=(), dtype=float32, numpy=0.9714>]